apiVersion: v1
kind: Service
metadata:
  name: fuckyou
spec:
  selector:
    app: fuckyou
  ports:
    - protocol: TCP
      name: http
      port: 8080
      targetPort: 8080
    - protocol: TCP
      name: prometheus
      port: 9090
      targetPort: 9090